"""rename to object_id

Revision ID: 09f038b17fcc
Revises: 939a23f176dc
Create Date: 2024-09-08 21:16:06.870782

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "09f038b17fcc"
down_revision: Union[str, None] = "939a23f176dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted ###
    # Добавляем колонку 'order'
    op.add_column(
        "dashboard_chart",
        sa.Column("order", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "dashboard_widget",
        sa.Column("order", sa.Integer(), nullable=False, server_default="0"),
    )

    # Переименовываем 'chart_id' в 'object_id' в таблице 'dashboard_chart'
    op.alter_column("dashboard_chart", "chart_id", new_column_name="object_id")

    # Обновляем внешний ключ после переименования
    op.drop_constraint(
        "dashboard_chart_chart_id_fkey", "dashboard_chart", type_="foreignkey"
    )
    op.create_foreign_key(None, "dashboard_chart", "chart", ["object_id"], ["id"])

    # Переименовываем 'widget_id' в 'object_id' в таблице 'dashboard_widget'
    op.alter_column("dashboard_widget", "widget_id", new_column_name="object_id")

    # Обновляем внешний ключ после переименования
    op.drop_constraint(
        "dashboard_widget_widget_id_fkey", "dashboard_widget", type_="foreignkey"
    )
    op.create_foreign_key(None, "dashboard_widget", "widget", ["object_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted ###
    # Удаляем колонку 'order'
    op.drop_column("dashboard_chart", "order")
    op.drop_column("dashboard_widget", "order")

    # Переименовываем 'object_id' обратно в 'chart_id' в таблице 'dashboard_chart'
    op.alter_column("dashboard_chart", "object_id", new_column_name="chart_id")

    # Восстанавливаем внешний ключ
    op.drop_constraint(None, "dashboard_chart", type_="foreignkey")
    op.create_foreign_key(
        "dashboard_chart_chart_id_fkey",
        "dashboard_chart",
        "chart",
        ["chart_id"],
        ["id"],
    )

    # Переименовываем 'object_id' обратно в 'widget_id' в таблице 'dashboard_widget'
    op.alter_column("dashboard_widget", "object_id", new_column_name="widget_id")

    # Восстанавливаем внешний ключ
    op.drop_constraint(None, "dashboard_widget", type_="foreignkey")
    op.create_foreign_key(
        "dashboard_widget_widget_id_fkey",
        "dashboard_widget",
        "widget",
        ["widget_id"],
        ["id"],
    )
    # ### end Alembic commands ###
