"""info_field

Revision ID: 2a4170aa537c
Revises: dcc25c0b2217
Create Date: 2025-04-04 15:01:28.156013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a4170aa537c'
down_revision: Union[str, None] = 'dcc25c0b2217'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('info', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data', 'info')
    # ### end Alembic commands ###
