"""temporary_table

Revision ID: 2f2b0aff7eac
Revises: 063650ea94eb
Create Date: 2025-03-12 22:12:15.840622

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f2b0aff7eac"
down_revision: Union[str, None] = "063650ea94eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "temporary_link",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("secret_link", sa.UUID(), nullable=True),
        sa.Column("available_until", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"],
            ["dashboard.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("temporary_link")
    # ### end Alembic commands ###
