"""add data relation

Revision ID: 354584f741a5
Revises: 9f1c54b22dad
Create Date: 2024-07-24 17:06:24.131704

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '354584f741a5'
down_revision: Union[str, None] = '9f1c54b22dad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('account', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'data', 'account', ['account'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data', type_='foreignkey')
    op.drop_column('data', 'account')
    # ### end Alembic commands ###
