"""dashboard relations account relation

Revision ID: 3e2aac5bc69d
Revises: 46c92d64b26e
Create Date: 2024-09-02 23:33:56.885148

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3e2aac5bc69d'
down_revision: Union[str, None] = '46c92d64b26e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboard', sa.Column('account', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'dashboard', 'account', ['account'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dashboard', type_='foreignkey')
    op.drop_column('dashboard', 'account')
    # ### end Alembic commands ###
