"""data_index

Revision ID: 40b48ae383ff
Revises: 2a4170aa537c
Create Date: 2025-04-04 15:31:21.656436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40b48ae383ff'
down_revision: Union[str, None] = '2a4170aa537c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_data_id_account', 'data', ['id', 'account'], unique=False)
    op.create_index('ix_data_title', 'data', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_data_title', table_name='data')
    op.drop_index('ix_data_id_account', table_name='data')
    # ### end Alembic commands ###
