"""dashboard relations

Revision ID: 46c92d64b26e
Revises: ce9ec068f345
Create Date: 2024-09-02 20:47:01.074717

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46c92d64b26e'
down_revision: Union[str, None] = 'ce9ec068f345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_chart',
    sa.Column('dashboard_id', sa.UUID(), nullable=False),
    sa.Column('chart_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['chart_id'], ['chart.id'], ),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboard.id'], ),
    sa.PrimaryKeyConstraint('dashboard_id', 'chart_id')
    )
    op.create_table('dashboard_widget',
    sa.Column('dashboard_id', sa.UUID(), nullable=False),
    sa.Column('widget_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboard.id'], ),
    sa.ForeignKeyConstraint(['widget_id'], ['widget.id'], ),
    sa.PrimaryKeyConstraint('dashboard_id', 'widget_id')
    )
    op.add_column('dashboard', sa.Column('settings', sa.JSON(), nullable=False))
    op.drop_column('dashboard', 'items')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboard', sa.Column('items', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('dashboard', 'settings')
    op.drop_table('dashboard_widget')
    op.drop_table('dashboard_chart')
    # ### end Alembic commands ###
