"""is_blocked fields

Revision ID: 6a72522dc053
Revises: 1d35fdbf4bb8
Create Date: 2024-07-22 14:49:53.878624

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6a72522dc053'
down_revision: Union[str, None] = '1d35fdbf4bb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('is_blocked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'is_blocked')
    # ### end Alembic commands ###
