"""create data model

Revision ID: 79e60263c381
Revises: a50975db2a1d
Create Date: 2024-07-23 14:45:23.142360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79e60263c381'
down_revision: Union[str, None] = 'a50975db2a1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('container', sa.JSON(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('time_create', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_update', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data')
    # ### end Alembic commands ###
