"""comment

Revision ID: 81c794d28fff
Revises: 09f038b17fcc
Create Date: 2024-09-09 14:54:34.765178

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "81c794d28fff"
down_revision: Union[str, None] = "09f038b17fcc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("dashboard_chart", "order", new_column_name="ordering")
    op.alter_column("dashboard_widget", "order", new_column_name="ordering")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("dashboard_chart", "ordering", new_column_name="order")
    op.alter_column("dashboard_widget", "ordering", new_column_name="order")
    # ### end Alembic commands ###
