"""nullable

Revision ID: b93a2325d724
Revises: 2f2b0aff7eac
Create Date: 2025-03-25 12:32:22.061378

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b93a2325d724"
down_revision: Union[str, None] = "2f2b0aff7eac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("chart", "data", existing_type=sa.UUID(), nullable=True)
    op.alter_column(
        "chart",
        "settings",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "data",
        "container",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column("widget", "data", existing_type=sa.UUID(), nullable=True)
    op.alter_column("widget", "data_column", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "widget", "offset_for_comparison", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "widget", "offset_for_comparison", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column("widget", "data_column", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("widget", "data", existing_type=sa.UUID(), nullable=False)
    op.alter_column(
        "data",
        "container",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "chart",
        "settings",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column("chart", "data", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
