"""widget update

Revision ID: ce9ec068f345
Revises: d59e5a0399d8
Create Date: 2024-08-24 20:33:21.000386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce9ec068f345'
down_revision: Union[str, None] = 'd59e5a0399d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('widget', sa.Column('data_column', sa.String(), nullable=False))
    op.add_column('widget', sa.Column('offset_for_comparison', sa.Integer(), nullable=False))
    op.drop_column('widget', 'settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('widget', sa.Column('settings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('widget', 'offset_for_comparison')
    op.drop_column('widget', 'data_column')
    # ### end Alembic commands ###
