"""is_reversed_widget

Revision ID: dcc25c0b2217
Revises: e77a53f3dca6
Create Date: 2025-04-04 14:57:56.413745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcc25c0b2217'
down_revision: Union[str, None] = 'e77a53f3dca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('widget', sa.Column('is_reversed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('widget', 'is_reversed')
    # ### end Alembic commands ###
